### ISSUE TITLE
question about the normalization on the attention weight

### ISSUE THREAD

**Issue by amiltonwong** [MenghaoGuo/PCT#13]
HI, @MenghaoGuo ,

From the code in [cls](https://github.com/MenghaoGuo/PCT/blob/main/networks/cls/pct.py#L217-L218) and [partseg](https://github.com/MenghaoGuo/PCT/blob/main/networks/seg/pct_partseg.py#L83-L84), the attention weights are already normalized by `self.softmax()`. Why did you add an extra line `attention / (1e-9 + attention.sum(dim=1, keepdims=True))` for weight normalization ? 

Any particular reason?

Thanks~

**Comment by MenghaoGuo** [comment]
Hi, 
Good question.
Please be care for the dimension of normalization, in the experiments, we find this way can make the training process more stable.
