### ISSUE TITLE
关于seg文件中似乎没有local feature representation的问题

### ISSUE THREAD

**Issue by 294coder** [MenghaoGuo/PCT#21]
Dear MenghaoGuo，

感谢你的代码，我在你的文章中的3.4节看到local feature representation，但是似乎这个操作只有cls里面有，seg文件中并没有文章提到的SG layer。
是分割任务中不需要local feature吗，还是global feature就已经能胜任分割任务？
希望您解答我的问题。

Thanks again！

**Comment by MenghaoGuo** [comment]
local feature 在分割里也是需要的，这里开源的是 SPCT 的分割代码。

**Comment by 294coder** [comment]
所以，这里的分割代码不是FPCT？

**Comment by MenghaoGuo** [comment]
是 SPCT， PCT 的分割代码有一部分没整理出来。

**Comment by 294coder** [comment]
好的，再次感谢😊
