### ISSUE TITLE
How is the Global Feature concatenated with Point Feature in segmentation?

### ISSUE THREAD

**Issue by YifanDengWHU** [MenghaoGuo/PCT#22]
Hi, thanks for your great work!
However, I have a problem with the concatenation in segmentation. As shown in Fig. 2, the _global feature_ is obtained by repeating its previous vector. It should be (batch_size, 1024, _point_num_), _point_num_ may be 1024 in the modelnet. While the point feature should be (batch_sie, 1024, _sampled_point_num_). For example, the _sample_point_num_ is 256 according to the implementation at https://github.com/Strawberry-Eat-Mango/PCT_Pytorch. 
So how can these two features be concatenated? Or do we just segment those sampled points?

**Comment by MenghaoGuo** [comment]
Hi,
in segmentation, we do not use downsample strategy , the point_num is always 2048.

**Comment by YifanDengWHU** [comment]
Got it, thanks!

**Comment by GCH-upup** [comment]
Hi，How do you implement segmentation code?
