### ISSUE TITLE
the code about attention map

### ISSUE THREAD

**Issue by kingziqiao** [MenghaoGuo/PCT#3]
Thank you very much for your work. Could you please provide me with the code for drawing the attention map, like this

**Comment by MenghaoGuo** [comment]
We draw the attention map with the support of meshlab. The code of drawing attention map is simply saving .txt file. 
The attention map can be drawed by following steps:
1. Choose query point i.
2. Convert the value of attention A[i,j] to the depth of color and save both position and color of all point j as .txt file
3. Open the saved .txt file by meshlab to render point cloud.
