### ISSUE TITLE
about a real example code

### ISSUE THREAD

**Issue by amiltonwong** [MenghaoGuo/PCT#6]
Hi, @MenghaoGuo ,

Thanks for releasing the package. The current package only provides the code for network construction. Could you provide a real example code for point cloud classification or segmentation?

Thanks~

**Comment by MenghaoGuo** [comment]
Hi, I'm willing to release all code and trained models.  But now I am preparing for the final exam and SIGGRAPH 2021.  Complete code and models will be organized and released after the submission deadline of SIGGRAPH 2021.

**Comment by amiltonwong** [comment]
Hi, @MenghaoGuo ,

Any news on the release for a real example?

THX!

**Comment by GCH-upup** [comment]
Hi, Will complete code and models  be released  after the submission deadline of SIGGRAPH 2021?
