### ISSUE TITLE
Reshape operation in Local_op

### ISSUE THREAD

**Issue by shift9172** [MenghaoGuo/PCT#7]
In Local_op module, it seems like you reshaped the 4-dimension feature from sample_and_group module [batch, npoint, nsample, features] to [batch * npoint, features, nsample]. Then feed it into 1d convolution. After that, you keep the biggst feature as [batch * npoint, features, 1], and reshape it to [batch, features, npoint].
In my opinion, this is the most significant difference between you and other pointnet series articles. Could you explain the effectiveness of this?

**Comment by MenghaoGuo** [comment]
I think it is the different implementations of same method with other pointnet series papers.
